# Generated by Django 5.0.4 on 2024-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.FileField(blank=True, null=True, upload_to='path/documents'),
        ),
    ]
