# Generated by Django 5.0.4 on 2024-04-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_alter_document_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='text',
            new_name='path',
        ),
    ]
