# Generated by Django 5.0.4 on 2024-04-16 22:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_rename_text_document_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='uploads/')),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='path',
        ),
    ]
